export const positions = [
    {
      title: "흥도초등학교 앞 돌다리",
      latlng: { lat: 36.3344624, lng: 127.3342898 },
      img: "https://ifh.cc/g/pFGAk4.jpg",
      imgs: "https://ifh.cc/g/pFGAk4.jpg",
      address: "대한민국 대전광역시 유성구 상대동 488",
      text: "",
    },
    {
      title: "대전시립박물관, 화장실",
      latlng: { lat: 36.3350338, lng: 127.3349251 },
      img: "https://ifh.cc/g/bo2OM9.jpg",
      imgs: "https://ifh.cc/g/bo2OM9.jpg@https://ifh.cc/g/lNzq7Q.jpg@https://ifh.cc/g/Fj0G1k.jpg@https://ifh.cc/g/FMcYlK.jpg",
      address: "대한민국 대전광역시 유성구 원신흥동 577",
      text: "",
    },
    {
      title: "원신흥 도서관 앞 돌다리",
      latlng: { lat: 36.3373248, lng: 127.3359853 },
      img: "https://ifh.cc/g/8BvJov.jpg",
      imgs: "https://ifh.cc/g/8BvJov.jpg@https://ifh.cc/g/J4LZ3v.jpg",
      address: "대한민국 대전광역시 유성구 상대동 501",
      text: "",
    },
    {
      title: "도안마을 10단지 돌다리, 정자",
      latlng: { lat: 36.341014, lng: 127.3390428 },
      img: "https://ifh.cc/g/2F1464.jpg",
      imgs: "https://ifh.cc/g/2F1464.jpg@https://ifh.cc/g/BQRscY.jpg@https://ifh.cc/g/g1doQ8.jpg",
      address: "대한민국 대전광역시 유성구 상대동 482-4",
      text: "",
    },
    {
      title: "고려교, 생활체육시설",
      latlng: { lat: 36.341677, lng: 127.3400296 },
      img: "https://ifh.cc/g/S9rMVY.jpg",
      imgs: "https://ifh.cc/g/S9rMVY.jpg@https://ifh.cc/g/PwpF0S.jpg@https://ifh.cc/g/lltMFB.jpg",
      address: "대한민국 대전광역시 유성구 상대동 501-1",
      text: "",
    },
    {
      title: "봉명서로 돌다리",
      latlng: { lat: 36.3438707, lng: 127.3431612 },
      img: "https://ifh.cc/g/9afp1R.jpg",
      imgs: "https://ifh.cc/g/9afp1R.jpg",
      address: "대한민국 대전광역시 유성구 봉명서로20번길 36",
      text: "",
    },
    {
      title: "봉명동 다리",
      latlng: { lat: 36.3472599, lng: 127.3491185 },
      img: "https://ifh.cc/g/vyc83G.jpg",
      imgs: "https://ifh.cc/g/vyc83G.jpg",
      address: "대한민국 대전광역시 유성구 봉명동 998",
      text: "",
    },
    {
      title: "갑천 우드골프장",
      latlng: { lat: 36.3502836, lng: 127.3487138 },
      img: "https://ifh.cc/g/dnszAW.jpg",
      imgs: "https://ifh.cc/g/dnszAW.jpg@https://ifh.cc/g/QOzlS1.jpg",
      address: "대한민국 대전광역시 유성구 봉명동 337-1 갑천 우드골프장",
      text: "#체육시설 #화장실 #골프장",
    },
    {
      title: "갑천 자전거도로 가로수길, 화장실",
      latlng: { lat: 36.3533041, lng: 127.3496172 },
      img: "https://ifh.cc/g/09gLD2.jpg",
      imgs: "https://ifh.cc/g/09gLD2.jpg@https://ifh.cc/g/9Yrdh0.jpg@https://ifh.cc/g/4XW2s7.jpg",
      address: "대한민국 대전광역시 유성구 봉명동 541-17",
      text: "",
    },
    {
      title: "가로수길 통로",
      latlng: { lat: 36.3558545, lng: 127.3524655 },
      img: "https://ifh.cc/g/RSysNN.jpg",
      imgs: "https://ifh.cc/g/RSysNN.jpg@https://ifh.cc/g/5W53Bl.jpg@https://ifh.cc/g/vt9hsA.jpg@https://ifh.cc/g/61AYDo.jpg@https://ifh.cc/g/Xnypq3.jpg",
      address: "대한민국 대전광역시 유성구 봉명동 500",
      text: "밤에 빛나옴",
    },
    {
      title: "갑천근린공원 근처 그늘 쉼터",
      latlng: { lat: 36.3575674, lng: 127.3552846 },
      img: "https://ifh.cc/g/N6t3aK.jpg",
      imgs: "https://ifh.cc/g/N6t3aK.jpg@https://ifh.cc/g/pMMWlS.jpg",
      address: "대한민국 대전광역시 유성구 봉명동 699",
      text: "",
    },
    {
      title: "무너진 다리",
      latlng: { lat: 36.3618656, lng: 127.3609571 },
      img: "https://ifh.cc/g/1ns98r.jpg",
      imgs: "https://ifh.cc/g/1ns98r.jpg",
      address: "대한민국 대전광역시 서구 월평동 1621",
      text: "",
    },
    {
      title: "유림공원 가는길 자전거도로",
      latlng: { lat: 36.3633685, lng: 127.3602875 },
      img: "https://ifh.cc/g/w0TR7R.jpg",
      imgs: "https://ifh.cc/g/w0TR7R.jpg@https://ifh.cc/g/OCdms1.jpg",
      address: "대한민국 대전광역시 유성구 구성동 317-3",
      text: "밤에 빛 쫙나옴",
    },
    {
      title: "체육공원 공중화장실",
      latlng: { lat: 36.366755, lng: 127.3668591 },
      img: "https://ifh.cc/g/ABFj5f.jpg",
      imgs: "https://ifh.cc/g/ABFj5f.jpg",
      address: "대한민국 대전광역시 유성구 구성동 276-1",
      text: "",
    },
    {
      title: "구성삼거리앞 그늘쉼터",
      latlng: { lat: 36.3692158, lng: 127.3708442 },
      img: "https://ifh.cc/g/vCYJH5.jpg",
      imgs: "https://ifh.cc/g/vCYJH5.jpg@https://ifh.cc/g/qVqs6K.jpg@https://ifh.cc/g/r5X0oL.jpg",
      address: "대한민국 대전광역시 유성구 구성동 466",
      text: "",
    },
    {
      title: "계단쉼터",
      latlng: { lat: 36.3719273, lng: 127.3755544 },
      img: "https://ifh.cc/g/aACMOX.jpg",
      imgs: "https://ifh.cc/g/aACMOX.jpg@https://ifh.cc/g/P0mM84.jpg",
      address: "대한민국 대전광역시 금강유역환경청",
      text: "",
    },
    {
      title: "유림공원 전망대",
      latlng: { lat: 36.3624742, lng: 127.3611769 },
      img: "https://ifh.cc/g/7pdmV2.jpg",
      imgs: "https://ifh.cc/g/7pdmV2.jpg@https://ifh.cc/g/nyhGoT.jpg@https://ifh.cc/g/R2J1zV.jpg",
      address: "대한민국 대전광역시 유성구 봉명동 유림공원 전망대",
      text: "",
    },
    {
      title: "엑스포 다리",
      latlng: { lat: 36.3716644, lng: 127.3880324 },
      img: "https://ifh.cc/g/oabLrQ.jpg",
      imgs: "https://ifh.cc/g/oabLrQ.jpg@https://ifh.cc/g/oo7gHX.jpg@https://ifh.cc/g/Tjnr97.jpg@https://ifh.cc/g/sLJdAg.jpg",
      address: "대한민국 대전광역시 유성구 도룡동 ",
      text: "",
    },
    {
      title: "스노우 글로브",
      latlng: { lat: 36.375935, lng: 127.38800151 },
      img: "https://ifh.cc/g/9T6SoY.jpg",
      imgs: "https://ifh.cc/g/9T6SoY.jpg@https://ifh.cc/g/n9T4ot.jpg@https://ifh.cc/g/K5wXSr.jpg",
      address: "대한민국 대전광역시 유성구 가정동 49-3 ",
      text: "",
    },
  ];